var packageInfo = require('../package.json');
function getPackageInfo() {
	return packageInfo;
}
const MAX_RETRIES=30;
const MAXDELAY=5000;
const TICK="TICK";
const HOUR="HOUR";
const MINUTE="MINUTE";
const DAY="DAY";
const WEEK="WEEK";
const MONTH="MONTH";

const AUTHENTICATE="Authenticate";
const GET_EXCHANGES="GetExchanges";
const GET_INSTRUMENTS_ON_SEARCH="GetInstrumentsOnSearch";
const GET_INSTRUMENTS="GetInstruments";
const GET_LAST_QUOTE="GetLastQuote";
const GET_LAST_QUOTE_ARRAY="GetLastQuoteArray";
const GET_SNAPSHOT="GetSnapshot";
const GET_HISTORY="GetHistory";
const GET_INSTRUMENT_TYPES= "GetInstrumentTypes";
const GET_PRODUCTS="GetProducts";
const GET_EXPIRY_DATES="GetExpiryDates";
const GET_OPTION_TYPES="GetOptionTypes";
const GET_STRIKE_PRICES="GetStrikePrices";
const GET_LIMITATIONS="GetLimitation";
const GET_SERVER_INFO="GetServerInfo";
const GET_MARKET_MESSAGE="GetMarketMessages";
const GET_EXCHANGE_MESSAGE="GetExchangeMessages";
const SUBSCRIBE_REAL_TIME="SubscribeRealtime";
const SUBSCRIBE_SNAPSHOT="SubscribeSnapshot";

const MESSAGE_EXCHANGE_RESULT="ExchangesResult";
const MESSAGE_INSTRUMENTS_ON_SEARCH_RESULT="InstrumentsOnSearchResult";
const MESSAGE_INSTRUMENTS_RESULT="InstrumentsResult";
const MESSAGE_LAST_QUOTE_RESULT="LastQuoteResult";
const MESSAGE_LAST_QUOTE_ARRAY_RESULT="LastQuoteArrayResult";
const MESSAGE_SNAPSHOT_RESULT="SnapshotResult";
const MESSAGE_HISTORY_TICK_RESULT="HistoryTickResult";
const MESSAGE_HISTORY_OHLC_RESULT="HistoryOHLCResult";
const MESSAGE_INSTRUMENT_TYPES_RESULT="InstrumentTypesResult";
const MESSAGE_PRODUCTS_RESULT="ProductsResult";
const MESSAGE_EXPIRY_DATE_RESULT="ExpiryDatesResult";
const MESSAGE_OPTION_TYPES_RESULT="OptionTypesResult";
const MESSAGE_STRIKE_PRICES_RESULT="StrikePricesResult";
const MESSAGE_LIMITATION_RESULT="LimitationResult";
const MESSAGE_SERVER_INFO_RESULT="ServerInfoResult";
const MESSAGE_MARKET_MESSAGE_RESULT="MarketMessagesResult";
const MESSAGE_EXCHANGE_MESSAGE_RESULT="ExchangeMessagesResult";
const MESSAGE_REAL_TIME_RESULT="RealtimeResult";
const MESSAGE_REAL_TIME_SNAPSHOT_RESULT="RealtimeSnapshotResult";
const RESULT_NOT_PREPARED='{"Message:ResponseNotAvailable"}';

module.exports = {
	getPackageInfo: getPackageInfo,
	MAX_RETRIES,
	MAXDELAY,
	TICK,
	HOUR,
	MINUTE,
	DAY,
	WEEK,
	MONTH,
	AUTHENTICATE,
	GET_EXCHANGES,
	GET_INSTRUMENTS_ON_SEARCH,
	GET_INSTRUMENTS,
	GET_LAST_QUOTE,
	GET_LAST_QUOTE_ARRAY,
	GET_SNAPSHOT,
	GET_HISTORY,
	GET_INSTRUMENT_TYPES,
	GET_PRODUCTS,
	GET_EXPIRY_DATES,
	GET_OPTION_TYPES,
	GET_STRIKE_PRICES,
	GET_LIMITATIONS,
	GET_SERVER_INFO,
	GET_MARKET_MESSAGE,
	GET_EXCHANGE_MESSAGE,
	SUBSCRIBE_REAL_TIME,
	SUBSCRIBE_SNAPSHOT,
	MESSAGE_EXCHANGE_RESULT,
	MESSAGE_INSTRUMENTS_ON_SEARCH_RESULT,
	MESSAGE_INSTRUMENTS_RESULT,
	MESSAGE_LAST_QUOTE_RESULT,
	MESSAGE_LAST_QUOTE_ARRAY_RESULT,
	MESSAGE_SNAPSHOT_RESULT,
	MESSAGE_HISTORY_TICK_RESULT,
	MESSAGE_HISTORY_OHLC_RESULT,
	MESSAGE_INSTRUMENT_TYPES_RESULT,
	MESSAGE_PRODUCTS_RESULT,
	MESSAGE_EXPIRY_DATE_RESULT,
	MESSAGE_OPTION_TYPES_RESULT,
	MESSAGE_STRIKE_PRICES_RESULT,
	MESSAGE_LIMITATION_RESULT,
	MESSAGE_SERVER_INFO_RESULT,
	MESSAGE_MARKET_MESSAGE_RESULT,
	MESSAGE_EXCHANGE_MESSAGE_RESULT,
	MESSAGE_REAL_TIME_RESULT,
	MESSAGE_REAL_TIME_SNAPSHOT_RESULT,
	RESULT_NOT_PREPARED
};